model:
  path: assets/models/detr_resnet50_modified_class_embed_bbox_embed_mpk.tar.gz
io:
  image: assets/test_images/input.jpg
  output: sandbox/detr_object_detection/output.png
decode:
  confidence_threshold: 0.50
  max_draw: 50
  person_only: false
runtime:
  timeout_ms: 5000
  profile: false
  num_runs: 100
  verbose: false
