model:
  path: assets/models/reid_mpk.tar.gz
io:
  image1: assets/test-images-reid/tom_hanks_1.jpg
  image2: assets/test-images-reid/tom_hanks_2.jpg
  output_dir: sandbox/person-re-identification
output:
  type: both
comparison:
  metric: cosine
  threshold: 0.65
runtime:
  timeout_ms: 5000
  profile: false
