server:
  openai:
    host: 0.0.0.0
    port: 9998

  models:
    chat:
      # The first chat model is selected by default in the UI.
      - name: <primary-chat-model-name>
        path: <path-to-primary-chat-model-dir>
      - name: <secondary-chat-model-name>
        path: <path-to-secondary-chat-model-dir>
    asr:
      name: <asr-model-name>
      path: <path-to-asr-model-dir>

app:
  openai:
    client_host: 127.0.0.1
    port: 9998

  request:
    max_tokens: 128
    system_prompt: >-
      Answer clearly and concisely.

  web:
    host: 0.0.0.0
    port: 5000
    https: true

  rag:
    enabled: true
    embedding_model_dir: /media/nvme/llima/models/gte-small
