model:
  path: assets/models/yolo_v8n_mpk.tar.gz
  labels: examples/object-detection/yolov8-object-detector/common/coco_label.txt
io:
  input_dir: assets/test_images
  output_dir: sandbox/yolov8-object-detector
decode:
  score_threshold: 0.55
  nms_iou: 0.50
  max_detections: 100
runtime:
  timeout_ms: 5000
