server:
  openai:
    host: 0.0.0.0
    port: 9998

  models:
    chat:
      - name: gemma4
        path: assets/models/genai/gemma4-E2B-it
      - name: qwen3-vl-2b
        path: assets/models/genai/Qwen3-VL-2B-Instruct-GPTQ-a16w4
    asr:
      name: whisper-small
      path: assets/models/genai/whisper-small-a16w8

app:
  openai:
    client_host: 127.0.0.1
    port: 9998

  request:
    max_tokens: 128
    system_prompt: >-
      Answer clearly and concisely.

  web:
    host: 0.0.0.0
    port: 5000
    https: true

  rag:
    enabled: false
    embedding_model_dir: assets/models/genai/gte-small
