server:
  openai:
    host: 0.0.0.0
    port: 9998

  models:
    chat:
      name: gemma4
      path: assets/models/genai/gemma4-E2B-it
    asr:
      name: whisper-small
      path: assets/models/genai/whisper-small-a16w8

app:
  openai:
    client_host: 127.0.0.1
    port: 9998

  models:
    chat: gemma4
    asr: whisper-small

  request:
    max_tokens: 128
    system_prompt: >-
      Answer clearly and concisely.

  web:
    host: 0.0.0.0
    port: 5000
    https: true

  rag:
    enabled: false
