model:
  path: assets/models/open_pose_mpk.tar.gz

io:
  input_dir: assets/test_images
  output_dir: sandbox/human-pose-estimator

runtime:
  infer_size: 480
  timeout_ms: 5000
  upsample_factor: 4.0

decode:
  keypoint_score: 0.06
  nms_radius: 6
  paf_score: 0.02
  paf_success_ratio: 0.55
  paf_samples: 10
  min_valid_joints: 3
  min_avg_person_score: 0.2
